name: Full Transcript Build + Sync + Assistant Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

permissions:
  contents: write

env:
  GH_USER: forgedbyfreedom
  GH_PAT: ${{ secrets.FBF_PAT }}
  DASHBOARD_REPO: forgedbyfreedom/forged-by-freedom-st
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  ASSISTANT_ID: asst_YOUR_ASSISTANT_ID_HERE  # 👈 Replace this with your real assistant ID

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout thinkbig-transcripts repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "🔧 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install requests openai beautifulsoup4 tqdm

      - name: Build and upload transcripts to OpenAI
        run: |
          echo "📘 Building and uploading transcripts..."
          python3 <<'PYCODE'
          import os, json, time
          from pathlib import Path
          from openai import OpenAI

          client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
          root = Path(".")
          file_index = []

          for folder in root.iterdir():
              if folder.is_dir() and folder.name.startswith("@"):
                  out_file = folder / "master_transcript1.txt"
                  with open(out_file, "w", encoding="utf-8") as outfile:
                      for txt in folder.rglob("*.txt"):
                          with open(txt, "r", encoding="utf-8", errors="ignore") as infile:
                              outfile.write(infile.read().strip() + "\n\n")
                  print(f"✅ Combined transcript for {folder.name}")

                  with open(out_file, "rb") as f:
                      uploaded = client.files.create(file=f, purpose="assistants")
                      file_index.append({
                          "channel": folder.name,
                          "filename": out_file.name,
                          "file_id": uploaded.id,
                          "size_bytes": os.path.getsize(out_file),
                          "uploaded_at": time.strftime("%Y-%m-%d %H:%M:%S")
                      })

          with open("file_index.json", "w", encoding="utf-8") as f:
              json.dump(file_index, f, indent=2)

          print("🎯 Uploaded all transcripts and created file_index.json")
          PYCODE

      - name: Commit updated transcripts locally
        run: |
          echo "💾 Committing updates to thinkbig-transcripts..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add . || true
          git commit -m "Auto update transcripts + file index [skip ci]" || echo "ℹ️ No changes."
          git push origin main || true

      - name: Sync transcripts to dashboard repo
        run: |
          echo "🚀 Syncing transcripts and index to dashboard repo..."
          git clone https://${GH_USER}:${GH_PAT}@github.com/${DASHBOARD_REPO}.git /tmp/dashboard
          mkdir -p /tmp/dashboard/transcripts
          cp */master_transcript1.txt /tmp/dashboard/transcripts/ 2>/dev/null || true
          cp file_index.json /tmp/dashboard/transcripts/

          cd /tmp/dashboard
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add transcripts/
          git commit -m "Sync master transcripts + index from thinkbig-transcripts [skip ci]" || echo "ℹ️ No changes."
          git push origin main || true

      - name: Update OpenAI Assistant
        run: |
          echo "🤖 Updating OpenAI Assistant with new files..."
          python3 <<'PYCODE'
          import os, json
          from openai import OpenAI

          api_key = os.getenv("OPENAI_API_KEY")
          asst_id = os.getenv("ASSISTANT_ID")
          if not api_key or not asst_id:
              print("⚠️ Missing OPENAI_API_KEY or ASSISTANT_ID — skipping assistant update.")
              raise SystemExit(0)

          client = OpenAI(api_key=api_key)

          with open("file_index.json", "r") as f:
              file_index = json.load(f)

          file_ids = [entry["file_id"] for entry in file_index]

          print(f"🔗 Linking {len(file_ids)} files to assistant {asst_id}...")
          client.beta.assistants.update(asst_id, file_ids=file_ids)
          print("✅ Assistant successfully updated with latest transcripts.")
          PYCODE
