name: Full Transcript Build + Deduplication + Pinecone Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # every night at 3 AM UTC

permissions:
  contents: write

env:
  GH_USER: forgedbyfreedom
  GH_PAT: ${{ secrets.FBF_PAT }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
  PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
  PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          echo "🔧 Installing dependencies..."
          python -m pip install --upgrade pip
          pip install openai pinecone-client tqdm python-dotenv requests beautifulsoup4

      - name: Build master transcripts
        run: |
          echo "🧩 Building and deduplicating transcripts..."
          python3 transcripts/auto_full_pipeline.py || echo "⚠️ Skipped local rebuild (no new data)"

      - name: Sync deduped transcripts to Pinecone
        run: |
          echo "🚀 Syncing transcripts to Pinecone..."
          python3 transcripts/sync_transcripts_to_pinecone.py || echo "⚠️ Pinecone sync skipped if already current"

      - name: Commit updated transcripts
        run: |
          echo "💾 Committing deduped transcript updates..."
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add transcripts/ file_index.json || true

          if git diff --cached --quiet; then
            echo "ℹ️ No new transcript updates detected."
            exit 0
          fi

          git commit -m "Auto update transcripts + Pinecone sync [skip ci]" || true
          git push https://${GH_USER}:${GH_PAT}@github.com/${GH_USER}/forged-by-freedom.git main || true
